version: '3.3'

services:
  
  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'billdb'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql/
    healthcheck: 
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '--user=root', '--password=root']
      interval: 3s
      timeout: 7s
      retries: 15
  
  pythonapp:
    build: ./pythonapp/
    ports:
      - 8089:5000
    volumes:
      - type: bind
        source: ./pythonapp/in/
        target: /in/
      - type: volume
        source: backups
        target: /rates_backups/
        volume:
          nocopy: true
    command: sh -c "python3 billing.py"
    depends_on:
      mysql:
        condition: service_healthy  

volumes:
  mysql-data:
    driver: local
  backups: