version: '3.3'

services:
  
  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'billdb'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql/
  
  pythonapp:
    build: ./pythonapp/
    ports:
      - 8089:5000
    command: sh -c "python3 billing.py"
    depends_on:
      - mysql  

volumes:
  mysql-data:
    driver: local