version: '3.3'

services:
pythonapp:
    build: ./pythonapp/
    environment:
      - WEIGHT_APP_PORT=${WEIGHT_APP_PORT}
      - BILLING_APP_PORT=${BILLING_APP_PORT}
    ports:
      - ${BILLING_APP_PORT}:5000
    volumes:
      - type: bind
        source: ./pythonapp/in/
        target: /in/
      - type: volume
        source: backups
        target: /rates_backups/
        volume:
          nocopy: true
    command: sh -c "python3 billing.py"
    depends_on:
      billmysql:
        condition: service_healthy  


  
  billmysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'billdb'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - mysql-data:/var/lib/mysql/
    healthcheck: 
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '--user=root', '--password=root']
      timeout: 7s
      retries: 15
      start_period: 30s
  
  
volumes:
  mysql-data:
    driver: local
  backups:

networks: 
  default: 
    name: ${NETWORK}
    external: true
