version: '3'
services:
  app_weight:
    build: ./app/
    ports:
      - "5010:5000"
    command: /bin/bash -c "python3 weight.py"  
    depends_on:
      my_data:
        condition: service_healthy 

  my_data:
    build: ./my_sql/
    environment:
      MYSQL_DATABASE: weight
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - weight_sql:/var/lib/mysql
    healthcheck: # check the healthiness with the following configuration
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '--user=root', '--password=root']
      interval: 3s
      timeout: 7s
      retries: 15

volumes:
  weight_sql:
    driver: local
  